version: '3.8'

services:
  web:
    build: ./
    command: flask run --port=5000 --host="0.0.0.0"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "haslO1234_"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433