"""empty message

Revision ID: f74711eadff2
Revises: 
Create Date: 2022-08-06 20:25:10.670344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74711eadff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contains',
    sa.Column('contains_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('contains_id')
    )
    op.create_table('family',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=True),
    sa.Column('language_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('library',
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(length=50), nullable=True),
    sa.Column('library_create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_table('pairs',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('pair_level', sa.Integer(), nullable=True),
    sa.Column('pair_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('pair_id')
    )
    op.create_table('play',
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('play_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('play_id')
    )
    op.create_table('relation',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('translation',
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('translation_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('use',
    sa.Column('use_id', sa.Integer(), nullable=False),
    sa.Column('use_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('use_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=50), nullable=True),
    sa.Column('user_password', sa.String(length=100), nullable=True),
    sa.Column('user_password_salt', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_name', sa.String(length=50), nullable=True),
    sa.Column('word_context', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('user')
    op.drop_table('use')
    op.drop_table('translation')
    op.drop_table('relation')
    op.drop_table('play')
    op.drop_table('pairs')
    op.drop_table('library')
    op.drop_table('language')
    op.drop_table('family')
    op.drop_table('contains')
    # ### end Alembic commands ###
